/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    EducationSection: typeof import('./src/components/EducationSection.vue')['default']
    EduSegment: typeof import('./src/components/EduSegment.vue')['default']
    ExpCard: typeof import('./src/components/ExpCard.vue')['default']
    ExperienceSection: typeof import('./src/components/ExperienceSection.vue')['default']
    LanguagesSection: typeof import('./src/components/LanguagesSection.vue')['default']
    LinkElement: typeof import('./src/components/LinkElement.vue')['default']
    ResumeContainer: typeof import('./src/components/ResumeContainer.vue')['default']
    SkillCard: typeof import('./src/components/SkillCard.vue')['default']
    SkillsSection: typeof import('./src/components/SkillsSection.vue')['default']
  }
}
